[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-community/go-cfclient"

[[constraint]]
  name = "github.com/cloudfoundry/noaa"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/sonde-go"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
  version = "0.9.2"

[[constraint]]
  name = "github.com/wavefronthq/go-metrics-wavefront"
  branch = "master"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.3"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true
